config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'forecast/search', 'forecast#search'
  get 'forecast/search', 'forecast#index'

  root 'forecast#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/forecast_controller.rb
# frozen_string_literal: true

require './lib/services/weather_service'
require './lib/connections/weather_connection'
require './lib/connections/geo_location_connection'

# Handles requests to the forecast endpoints
class ForecastController < ApplicationController
  def index; end

  def search
    perform_search if params[:address]
    render 'index'
  rescue GeoLocationConnectionError, WeatherConnectionError => e
    process_error(e)
  end

  private

  def perform_search
    address = search_params
    @cache = true
    @location_name = "#{address[:city]}, #{address[:state]}, #{address[:zip]}"
    @forecast = Rails.cache.fetch("#{address[:zip]}/forecast", expires_in: 30.minutes) do
      logger.info("Cache miss for zip: #{address[:zip]}")
      @cache = false
      search_current_weather(address[:street], address[:city], address[:state], address[:zip])
    end
  end

  def search_current_weather(street, city, state, zip)
    weather_service = WeatherService.new(WeatherConnection.new, GeoLocationConnection.new)
    weather_service.current_weather(street, city, state, zip)
  end

  def process_error(error)
    logger.error(error)
    flash[:error] = error.message
    redirect_to action: 'index'
  end

  def search_params
    params.require(:address).permit(:street, :city, :state, :zip)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/forecast_helper.rb
# frozen_string_literal: true

module ForecastHelper
end

app/helpers/weather_helper.rb
# frozen_string_literal: true

module WeatherHelper
end

app/views/forecast/_current_weather.html.erb
<% if forecast.present? %>
  <h2>Current Forecast</h2>
  <% if cache %>
    <p>Cached</p>
  <% end %>
  <h3><%= location_name %></h3>

  <section>
    <div>
      <span>Description:</span>
      <span><%= forecast.description %></span>
    </div>
    <div>
      <span>Temperature:</span>
      <span><%= forecast.temperature %>&#8457;</span>
    </div>
    <div>
      <span>Feels Like:</span>
      <span><%= forecast.feels_like %>&#8457;</span>
    </div>
    <div>
      <span>High:</span>
      <span><%= forecast.high %>&#8457;</span>
    </div>
    <div>
      <span>Low:</span>
      <span><%= forecast.low %>&#8457;</span>
    </div>
  </section>
<% end %>

app/views/forecast/_forecast_search.html.erb
<%= form_with url: forecast_search_path, scope: :address, method: 'post' do |form| %>
  <span>
    <%= form.label :street, "Street Address:" %>
    <%= form.text_field :street, required: true %>
  </span>

  <span>
    <%= form.label :city, "City:" %>
    <%= form.text_field :city, required: true %>
  </span>

  <span>
    <%= form.label :state, "State:" %>
    <%= form.text_field :state, required: true %>
  </span>

  <span>
    <%= form.label :zip, "Zipcode:" %>
    <%= form.text_field :zip, required: true %>
  </span>

  <%= form.submit "Search" %>
<% end %>

app/views/forecast/index.html.erb
<h1>Weather Forecast</h1>

<%= render "forecast_search" %>

<%= render "current_weather", cache: @cache, forecast: @forecast, location_name: @location_name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if flash[:error] %>
      Error: <%= flash[:error] %>
    <% end %>
  </body>
</html>